import type {
  Store,
  Order,
  Shipment,
  ActivityEvent,
  WebhookEndpoint,
  WebhookDelivery,
} from "@merchantflow/shared-types";

// ── Stores ────────────────────────────────────────────────────────────────────

export const mockStores: Store[] = [
  {
    id: "store_01HQXYZ1A2B3C4D5E6F7G8H9J0",
    name: "Luminary Goods Co.",
    email: "ops@luminarygoods.com",
    shopifyDomain: "luminary-goods.myshopify.com",
    currency: "USD",
    timezone: "America/New_York",
    status: "ACTIVE",
    createdAt: "2025-11-15T08:30:00Z",
    updatedAt: "2026-03-28T14:22:00Z",
  },
  {
    id: "store_01HQXYZ2B3C4D5E6F7G8H9J0K1",
    name: "Pacific Trade Supply",
    email: "admin@pacifictrade.co",
    shopifyDomain: "pacific-trade-supply.myshopify.com",
    currency: "USD",
    timezone: "America/Los_Angeles",
    status: "ACTIVE",
    createdAt: "2026-01-22T10:15:00Z",
    updatedAt: "2026-03-27T09:45:00Z",
  },
  {
    id: "store_01HQXYZ3C4D5E6F7G8H9J0K1L2",
    name: "Nordic Essentials",
    email: "hello@nordicessentials.eu",
    shopifyDomain: "nordic-essentials.myshopify.com",
    currency: "EUR",
    timezone: "Europe/Stockholm",
    status: "SUSPENDED",
    createdAt: "2026-02-10T06:00:00Z",
    updatedAt: "2026-03-20T12:00:00Z",
  },
];

// ── Orders ────────────────────────────────────────────────────────────────────

const storeId = mockStores[0].id;

export const mockOrders: Order[] = [
  {
    id: "ord_01HQ0001",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5001",
    orderNumber: "#1001",
    subtotalPrice: "249.00",
    totalTax: "19.92",
    totalShipping: "12.99",
    totalDiscount: "0.00",
    totalPrice: "281.91",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "sarah.chen@example.com",
    customerFirstName: "Sarah",
    customerLastName: "Chen",
    customerPhone: "+1-415-555-0142",
    shippingAddress: {
      line1: "742 Evergreen Terrace",
      line2: "Apt 3B",
      city: "San Francisco",
      province: "CA",
      postalCode: "94102",
      countryCode: "US",
      phone: "+1-415-555-0142",
    },
    lineItems: [
      {
        id: "li_001",
        shopifyLineItemId: "gid://shopify/LineItem/9001",
        title: "Ceramic Pour-Over Set",
        variantTitle: "Matte Black",
        sku: "CER-PO-001-BLK",
        quantity: 1,
        unitPrice: "89.00",
        totalPrice: "89.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_002",
        shopifyLineItemId: "gid://shopify/LineItem/9002",
        title: "Organic Single-Origin Coffee Beans",
        variantTitle: "Ethiopian Yirgacheffe / 500g",
        sku: "COF-ETH-500",
        quantity: 2,
        unitPrice: "32.00",
        totalPrice: "64.00",
        fulfilledQuantity: 2,
      },
      {
        id: "li_003",
        shopifyLineItemId: "gid://shopify/LineItem/9003",
        title: "Walnut Coffee Scoop",
        variantTitle: null,
        sku: "WOD-SCO-WAL",
        quantity: 1,
        unitPrice: "24.00",
        totalPrice: "24.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_004",
        shopifyLineItemId: "gid://shopify/LineItem/9004",
        title: "Linen Tote Bag",
        variantTitle: "Natural",
        sku: "BAG-LIN-NAT",
        quantity: 1,
        unitPrice: "72.00",
        totalPrice: "72.00",
        fulfilledQuantity: 1,
      },
    ],
    shipments: [
      { id: "shp_01", status: "DELIVERED", carrier: "USPS", trackingNumber: "9400111899223456789012" },
    ],
    createdAt: "2026-03-15T09:12:00Z",
    updatedAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "ord_01HQ0002",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5002",
    orderNumber: "#1002",
    subtotalPrice: "159.00",
    totalTax: "12.72",
    totalShipping: "8.99",
    totalDiscount: "15.90",
    totalPrice: "164.81",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "james.rodriguez@example.com",
    customerFirstName: "James",
    customerLastName: "Rodriguez",
    customerPhone: "+1-212-555-0198",
    shippingAddress: {
      line1: "350 5th Avenue",
      line2: "Suite 3300",
      city: "New York",
      province: "NY",
      postalCode: "10118",
      countryCode: "US",
      phone: "+1-212-555-0198",
    },
    lineItems: [
      {
        id: "li_005",
        shopifyLineItemId: "gid://shopify/LineItem/9005",
        title: "Merino Wool Beanie",
        variantTitle: "Charcoal",
        sku: "APP-BEA-CHA",
        quantity: 2,
        unitPrice: "45.00",
        totalPrice: "90.00",
        fulfilledQuantity: 0,
      },
      {
        id: "li_006",
        shopifyLineItemId: "gid://shopify/LineItem/9006",
        title: "Leather Card Wallet",
        variantTitle: "Cognac",
        sku: "ACC-WAL-COG",
        quantity: 1,
        unitPrice: "69.00",
        totalPrice: "69.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-22T15:45:00Z",
    updatedAt: "2026-03-22T15:45:00Z",
  },
  {
    id: "ord_01HQ0003",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5003",
    orderNumber: "#1003",
    subtotalPrice: "425.00",
    totalTax: "34.00",
    totalShipping: "0.00",
    totalDiscount: "42.50",
    totalPrice: "416.50",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "PARTIALLY_FULFILLED",
    customerEmail: "emily.watson@example.com",
    customerFirstName: "Emily",
    customerLastName: "Watson",
    customerPhone: null,
    shippingAddress: {
      line1: "8812 Sunset Blvd",
      line2: null,
      city: "Los Angeles",
      province: "CA",
      postalCode: "90069",
      countryCode: "US",
      phone: null,
    },
    lineItems: [
      {
        id: "li_007",
        shopifyLineItemId: "gid://shopify/LineItem/9007",
        title: "Handwoven Throw Blanket",
        variantTitle: "Terracotta",
        sku: "HOM-THR-TER",
        quantity: 1,
        unitPrice: "185.00",
        totalPrice: "185.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_008",
        shopifyLineItemId: "gid://shopify/LineItem/9008",
        title: "Stoneware Dinner Set",
        variantTitle: "Sage / 4-Piece",
        sku: "KIT-DIN-SAG-4",
        quantity: 1,
        unitPrice: "240.00",
        totalPrice: "240.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [
      { id: "shp_03", status: "SHIPPED", carrier: "FedEx", trackingNumber: "794644790132" },
    ],
    createdAt: "2026-03-24T11:20:00Z",
    updatedAt: "2026-03-26T08:15:00Z",
  },
  {
    id: "ord_01HQ0004",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5004",
    orderNumber: "#1004",
    subtotalPrice: "54.00",
    totalTax: "4.32",
    totalShipping: "5.99",
    totalDiscount: "0.00",
    totalPrice: "64.31",
    currencyCode: "USD",
    financialStatus: "PENDING",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "marcus.lee@example.com",
    customerFirstName: "Marcus",
    customerLastName: "Lee",
    customerPhone: "+1-503-555-0176",
    shippingAddress: {
      line1: "1200 NW Lovejoy St",
      line2: null,
      city: "Portland",
      province: "OR",
      postalCode: "97209",
      countryCode: "US",
      phone: "+1-503-555-0176",
    },
    lineItems: [
      {
        id: "li_009",
        shopifyLineItemId: "gid://shopify/LineItem/9009",
        title: "Soy Candle Trio",
        variantTitle: "Cedar + Sage + Lavender",
        sku: "HOM-CAN-TRI",
        quantity: 1,
        unitPrice: "54.00",
        totalPrice: "54.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-27T08:30:00Z",
    updatedAt: "2026-03-27T08:30:00Z",
  },
  {
    id: "ord_01HQ0005",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5005",
    orderNumber: "#1005",
    subtotalPrice: "312.00",
    totalTax: "24.96",
    totalShipping: "14.99",
    totalDiscount: "31.20",
    totalPrice: "320.75",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "anna.kowalski@example.com",
    customerFirstName: "Anna",
    customerLastName: "Kowalski",
    customerPhone: "+1-312-555-0133",
    shippingAddress: {
      line1: "233 S Wacker Dr",
      line2: "Floor 42",
      city: "Chicago",
      province: "IL",
      postalCode: "60606",
      countryCode: "US",
      phone: "+1-312-555-0133",
    },
    lineItems: [
      {
        id: "li_010",
        shopifyLineItemId: "gid://shopify/LineItem/9010",
        title: "Brass Desk Lamp",
        variantTitle: "Antique Finish",
        sku: "LIT-DLP-BRS",
        quantity: 1,
        unitPrice: "195.00",
        totalPrice: "195.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_011",
        shopifyLineItemId: "gid://shopify/LineItem/9011",
        title: "Recycled Paper Notebook Set",
        variantTitle: "A5 / 3-Pack",
        sku: "STA-NB-A5-3",
        quantity: 3,
        unitPrice: "39.00",
        totalPrice: "117.00",
        fulfilledQuantity: 3,
      },
    ],
    shipments: [
      { id: "shp_05", status: "DELIVERED", carrier: "UPS", trackingNumber: "1Z999AA10123456784" },
    ],
    createdAt: "2026-03-18T13:00:00Z",
    updatedAt: "2026-03-23T16:45:00Z",
  },
  {
    id: "ord_01HQ0006",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5006",
    orderNumber: "#1006",
    subtotalPrice: "89.00",
    totalTax: "7.12",
    totalShipping: "5.99",
    totalDiscount: "0.00",
    totalPrice: "102.11",
    currencyCode: "USD",
    financialStatus: "REFUNDED",
    fulfillmentStatus: "RESTOCKED",
    customerEmail: "david.park@example.com",
    customerFirstName: "David",
    customerLastName: "Park",
    customerPhone: "+1-206-555-0164",
    shippingAddress: {
      line1: "400 Broad St",
      line2: null,
      city: "Seattle",
      province: "WA",
      postalCode: "98109",
      countryCode: "US",
      phone: "+1-206-555-0164",
    },
    lineItems: [
      {
        id: "li_012",
        shopifyLineItemId: "gid://shopify/LineItem/9012",
        title: "Ceramic Pour-Over Set",
        variantTitle: "Cloud White",
        sku: "CER-PO-001-WHT",
        quantity: 1,
        unitPrice: "89.00",
        totalPrice: "89.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-10T16:20:00Z",
    updatedAt: "2026-03-14T09:00:00Z",
  },
  {
    id: "ord_01HQ0007",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5007",
    orderNumber: "#1007",
    subtotalPrice: "567.00",
    totalTax: "45.36",
    totalShipping: "0.00",
    totalDiscount: "56.70",
    totalPrice: "555.66",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "olivia.martinez@example.com",
    customerFirstName: "Olivia",
    customerLastName: "Martinez",
    customerPhone: "+1-305-555-0187",
    shippingAddress: {
      line1: "1100 Biscayne Blvd",
      line2: "PH-1",
      city: "Miami",
      province: "FL",
      postalCode: "33132",
      countryCode: "US",
      phone: "+1-305-555-0187",
    },
    lineItems: [
      {
        id: "li_013",
        shopifyLineItemId: "gid://shopify/LineItem/9013",
        title: "Handwoven Throw Blanket",
        variantTitle: "Indigo",
        sku: "HOM-THR-IND",
        quantity: 2,
        unitPrice: "185.00",
        totalPrice: "370.00",
        fulfilledQuantity: 0,
      },
      {
        id: "li_014",
        shopifyLineItemId: "gid://shopify/LineItem/9014",
        title: "Copper Watering Can",
        variantTitle: null,
        sku: "GAR-WTR-COP",
        quantity: 1,
        unitPrice: "128.00",
        totalPrice: "128.00",
        fulfilledQuantity: 0,
      },
      {
        id: "li_015",
        shopifyLineItemId: "gid://shopify/LineItem/9015",
        title: "Soy Candle Trio",
        variantTitle: "Cedar + Sage + Lavender",
        sku: "HOM-CAN-TRI",
        quantity: 1,
        unitPrice: "54.00",
        totalPrice: "54.00",
        fulfilledQuantity: 0,
      },
      {
        id: "li_016",
        shopifyLineItemId: "gid://shopify/LineItem/9016",
        title: "Cork Yoga Mat",
        variantTitle: "Standard",
        sku: "FIT-YM-CRK",
        quantity: 1,
        unitPrice: "15.00",
        totalPrice: "15.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-28T07:15:00Z",
    updatedAt: "2026-03-28T07:15:00Z",
  },
  {
    id: "ord_01HQ0008",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5008",
    orderNumber: "#1008",
    subtotalPrice: "145.00",
    totalTax: "11.60",
    totalShipping: "8.99",
    totalDiscount: "0.00",
    totalPrice: "165.59",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "michael.oconnor@example.com",
    customerFirstName: "Michael",
    customerLastName: "O'Connor",
    customerPhone: "+1-617-555-0155",
    shippingAddress: {
      line1: "4 Yawkey Way",
      line2: null,
      city: "Boston",
      province: "MA",
      postalCode: "02215",
      countryCode: "US",
      phone: "+1-617-555-0155",
    },
    lineItems: [
      {
        id: "li_017",
        shopifyLineItemId: "gid://shopify/LineItem/9017",
        title: "Leather Card Wallet",
        variantTitle: "Black",
        sku: "ACC-WAL-BLK",
        quantity: 1,
        unitPrice: "69.00",
        totalPrice: "69.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_018",
        shopifyLineItemId: "gid://shopify/LineItem/9018",
        title: "Stainless Steel Water Bottle",
        variantTitle: "Matte Olive / 750ml",
        sku: "DRK-BTL-OLV",
        quantity: 2,
        unitPrice: "38.00",
        totalPrice: "76.00",
        fulfilledQuantity: 2,
      },
    ],
    shipments: [
      { id: "shp_08", status: "IN_TRANSIT", carrier: "USPS", trackingNumber: "9400111899223456789099" },
    ],
    createdAt: "2026-03-21T10:40:00Z",
    updatedAt: "2026-03-25T11:20:00Z",
  },
  {
    id: "ord_01HQ0009",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5009",
    orderNumber: "#1009",
    subtotalPrice: "78.00",
    totalTax: "6.24",
    totalShipping: "5.99",
    totalDiscount: "0.00",
    totalPrice: "90.23",
    currencyCode: "USD",
    financialStatus: "AUTHORIZED",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "nina.patel@example.com",
    customerFirstName: "Nina",
    customerLastName: "Patel",
    customerPhone: "+1-512-555-0121",
    shippingAddress: {
      line1: "600 Congress Ave",
      line2: "Suite 200",
      city: "Austin",
      province: "TX",
      postalCode: "78701",
      countryCode: "US",
      phone: "+1-512-555-0121",
    },
    lineItems: [
      {
        id: "li_019",
        shopifyLineItemId: "gid://shopify/LineItem/9019",
        title: "Recycled Paper Notebook Set",
        variantTitle: "A5 / 3-Pack",
        sku: "STA-NB-A5-3",
        quantity: 2,
        unitPrice: "39.00",
        totalPrice: "78.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-28T16:55:00Z",
    updatedAt: "2026-03-28T16:55:00Z",
  },
  {
    id: "ord_01HQ0010",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5010",
    orderNumber: "#1010",
    subtotalPrice: "680.00",
    totalTax: "54.40",
    totalShipping: "0.00",
    totalDiscount: "68.00",
    totalPrice: "666.40",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "thomas.wright@example.com",
    customerFirstName: "Thomas",
    customerLastName: "Wright",
    customerPhone: "+1-720-555-0199",
    shippingAddress: {
      line1: "1600 Glenarm Pl",
      line2: null,
      city: "Denver",
      province: "CO",
      postalCode: "80202",
      countryCode: "US",
      phone: "+1-720-555-0199",
    },
    lineItems: [
      {
        id: "li_020",
        shopifyLineItemId: "gid://shopify/LineItem/9020",
        title: "Brass Desk Lamp",
        variantTitle: "Antique Finish",
        sku: "LIT-DLP-BRS",
        quantity: 2,
        unitPrice: "195.00",
        totalPrice: "390.00",
        fulfilledQuantity: 2,
      },
      {
        id: "li_021",
        shopifyLineItemId: "gid://shopify/LineItem/9021",
        title: "Handwoven Throw Blanket",
        variantTitle: "Terracotta",
        sku: "HOM-THR-TER",
        quantity: 1,
        unitPrice: "185.00",
        totalPrice: "185.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_022",
        shopifyLineItemId: "gid://shopify/LineItem/9022",
        title: "Soy Candle Trio",
        variantTitle: "Vanilla + Rose + Jasmine",
        sku: "HOM-CAN-TRI-FLR",
        quantity: 1,
        unitPrice: "54.00",
        totalPrice: "54.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_023",
        shopifyLineItemId: "gid://shopify/LineItem/9023",
        title: "Cork Coaster Set",
        variantTitle: "Set of 6",
        sku: "HOM-CST-CRK-6",
        quantity: 1,
        unitPrice: "51.00",
        totalPrice: "51.00",
        fulfilledQuantity: 1,
      },
    ],
    shipments: [
      { id: "shp_10", status: "DELIVERED", carrier: "FedEx", trackingNumber: "794644790188" },
    ],
    createdAt: "2026-03-12T14:10:00Z",
    updatedAt: "2026-03-19T09:30:00Z",
  },
  {
    id: "ord_01HQ0011",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5011",
    orderNumber: "#1011",
    subtotalPrice: "192.00",
    totalTax: "15.36",
    totalShipping: "8.99",
    totalDiscount: "0.00",
    totalPrice: "216.35",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "rachel.kim@example.com",
    customerFirstName: "Rachel",
    customerLastName: "Kim",
    customerPhone: "+1-404-555-0188",
    shippingAddress: { line1: "285 Peachtree Center Ave", line2: "NE", city: "Atlanta", province: "GA", postalCode: "30303", countryCode: "US", phone: null },
    lineItems: [
      { id: "li_024", shopifyLineItemId: "gid://shopify/LineItem/9024", title: "Linen Tote Bag", variantTitle: "Olive", sku: "BAG-LIN-OLV", quantity: 1, unitPrice: "72.00", totalPrice: "72.00", fulfilledQuantity: 0 },
      { id: "li_025", shopifyLineItemId: "gid://shopify/LineItem/9025", title: "Organic Cotton T-Shirt", variantTitle: "White / L", sku: "APP-TEE-WHT-L", quantity: 2, unitPrice: "42.00", totalPrice: "84.00", fulfilledQuantity: 0 },
      { id: "li_026", shopifyLineItemId: "gid://shopify/LineItem/9026", title: "Walnut Coffee Scoop", variantTitle: null, sku: "WOD-SCO-WAL", quantity: 1, unitPrice: "24.00", totalPrice: "24.00", fulfilledQuantity: 0 },
      { id: "li_027", shopifyLineItemId: "gid://shopify/LineItem/9027", title: "Cork Yoga Mat", variantTitle: "Standard", sku: "FIT-YM-CRK", quantity: 1, unitPrice: "12.00", totalPrice: "12.00", fulfilledQuantity: 0 },
    ],
    shipments: [],
    createdAt: "2026-03-28T19:30:00Z",
    updatedAt: "2026-03-28T19:30:00Z",
  },
  {
    id: "ord_01HQ0012",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5012",
    orderNumber: "#1012",
    subtotalPrice: "128.00",
    totalTax: "10.24",
    totalShipping: "12.99",
    totalDiscount: "0.00",
    totalPrice: "151.23",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "alex.thompson@example.com",
    customerFirstName: "Alex",
    customerLastName: "Thompson",
    customerPhone: null,
    shippingAddress: { line1: "1 Hacker Way", line2: null, city: "Menlo Park", province: "CA", postalCode: "94025", countryCode: "US", phone: null },
    lineItems: [
      { id: "li_028", shopifyLineItemId: "gid://shopify/LineItem/9028", title: "Copper Watering Can", variantTitle: null, sku: "GAR-WTR-COP", quantity: 1, unitPrice: "128.00", totalPrice: "128.00", fulfilledQuantity: 1 },
    ],
    shipments: [
      { id: "shp_12", status: "DELIVERED", carrier: "UPS", trackingNumber: "1Z999AA10123456790" },
    ],
    createdAt: "2026-03-14T08:00:00Z",
    updatedAt: "2026-03-20T10:15:00Z",
  },
  {
    id: "ord_01HQ0013",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5013",
    orderNumber: "#1013",
    subtotalPrice: "395.00",
    totalTax: "31.60",
    totalShipping: "0.00",
    totalDiscount: "39.50",
    totalPrice: "387.10",
    currencyCode: "USD",
    financialStatus: "PARTIALLY_PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "jessica.nguyen@example.com",
    customerFirstName: "Jessica",
    customerLastName: "Nguyen",
    customerPhone: "+1-714-555-0145",
    shippingAddress: { line1: "100 Universal City Plaza", line2: null, city: "Universal City", province: "CA", postalCode: "91608", countryCode: "US", phone: "+1-714-555-0145" },
    lineItems: [
      { id: "li_029", shopifyLineItemId: "gid://shopify/LineItem/9029", title: "Stoneware Dinner Set", variantTitle: "Charcoal / 4-Piece", sku: "KIT-DIN-CHR-4", quantity: 1, unitPrice: "240.00", totalPrice: "240.00", fulfilledQuantity: 0 },
      { id: "li_030", shopifyLineItemId: "gid://shopify/LineItem/9030", title: "Linen Table Runner", variantTitle: "Oatmeal", sku: "HOM-TBR-OAT", quantity: 1, unitPrice: "85.00", totalPrice: "85.00", fulfilledQuantity: 0 },
      { id: "li_031", shopifyLineItemId: "gid://shopify/LineItem/9031", title: "Beeswax Wrap Set", variantTitle: "3-Pack", sku: "KIT-BWX-3PK", quantity: 1, unitPrice: "28.00", totalPrice: "28.00", fulfilledQuantity: 0 },
      { id: "li_032", shopifyLineItemId: "gid://shopify/LineItem/9032", title: "Ceramic Spoon Rest", variantTitle: "Sage", sku: "KIT-SPR-SAG", quantity: 2, unitPrice: "21.00", totalPrice: "42.00", fulfilledQuantity: 0 },
    ],
    shipments: [],
    createdAt: "2026-03-29T02:10:00Z",
    updatedAt: "2026-03-29T02:10:00Z",
  },
  {
    id: "ord_01HQ0014",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5014",
    orderNumber: "#1014",
    subtotalPrice: "76.00",
    totalTax: "6.08",
    totalShipping: "5.99",
    totalDiscount: "0.00",
    totalPrice: "88.07",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "kevin.brown@example.com",
    customerFirstName: "Kevin",
    customerLastName: "Brown",
    customerPhone: "+1-602-555-0132",
    shippingAddress: { line1: "401 E Jefferson St", line2: null, city: "Phoenix", province: "AZ", postalCode: "85004", countryCode: "US", phone: "+1-602-555-0132" },
    lineItems: [
      { id: "li_033", shopifyLineItemId: "gid://shopify/LineItem/9033", title: "Stainless Steel Water Bottle", variantTitle: "Matte Black / 750ml", sku: "DRK-BTL-BLK", quantity: 2, unitPrice: "38.00", totalPrice: "76.00", fulfilledQuantity: 2 },
    ],
    shipments: [
      { id: "shp_14", status: "SHIPPED", carrier: "USPS", trackingNumber: "9400111899223456789055" },
    ],
    createdAt: "2026-03-19T12:35:00Z",
    updatedAt: "2026-03-24T08:00:00Z",
  },
  {
    id: "ord_01HQ0015",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5015",
    orderNumber: "#1015",
    subtotalPrice: "210.00",
    totalTax: "16.80",
    totalShipping: "8.99",
    totalDiscount: "21.00",
    totalPrice: "214.79",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "sophia.diaz@example.com",
    customerFirstName: "Sophia",
    customerLastName: "Diaz",
    customerPhone: "+1-619-555-0178",
    shippingAddress: { line1: "750 B St", line2: "Suite 1800", city: "San Diego", province: "CA", postalCode: "92101", countryCode: "US", phone: "+1-619-555-0178" },
    lineItems: [
      { id: "li_034", shopifyLineItemId: "gid://shopify/LineItem/9034", title: "Merino Wool Beanie", variantTitle: "Navy", sku: "APP-BEA-NAV", quantity: 1, unitPrice: "45.00", totalPrice: "45.00", fulfilledQuantity: 0 },
      { id: "li_035", shopifyLineItemId: "gid://shopify/LineItem/9035", title: "Cork Yoga Mat", variantTitle: "Standard", sku: "FIT-YM-CRK", quantity: 1, unitPrice: "95.00", totalPrice: "95.00", fulfilledQuantity: 0 },
      { id: "li_036", shopifyLineItemId: "gid://shopify/LineItem/9036", title: "Linen Tote Bag", variantTitle: "Natural", sku: "BAG-LIN-NAT", quantity: 1, unitPrice: "72.00", totalPrice: "72.00", fulfilledQuantity: 0 },
    ],
    shipments: [],
    createdAt: "2026-03-28T22:00:00Z",
    updatedAt: "2026-03-28T22:00:00Z",
  },
  // Additional orders for pagination
  ...generateBulkOrders(16, 25),
];

function generateBulkOrders(start: number, end: number): Order[] {
  const customers = [
    { first: "Liam", last: "Johnson", email: "liam.j@example.com" },
    { first: "Emma", last: "Davis", email: "emma.d@example.com" },
    { first: "Noah", last: "Wilson", email: "noah.w@example.com" },
    { first: "Ava", last: "Anderson", email: "ava.a@example.com" },
    { first: "William", last: "Taylor", email: "will.t@example.com" },
    { first: "Isabella", last: "Moore", email: "isabella.m@example.com" },
    { first: "Benjamin", last: "Jackson", email: "ben.j@example.com" },
    { first: "Mia", last: "Harris", email: "mia.h@example.com" },
    { first: "Lucas", last: "Clark", email: "lucas.c@example.com" },
    { first: "Charlotte", last: "Lewis", email: "charlotte.l@example.com" },
  ];

  const statuses: Array<{ fin: Order["financialStatus"]; ful: Order["fulfillmentStatus"] }> = [
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "PAID", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "PARTIALLY_FULFILLED" },
    { fin: "PENDING", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "AUTHORIZED", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "PAID", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "PARTIALLY_REFUNDED", ful: "FULFILLED" },
  ];

  const products = [
    { title: "Organic Cotton T-Shirt", sku: "APP-TEE-WHT-M", price: "42.00" },
    { title: "Merino Wool Scarf", sku: "APP-SCF-GRY", price: "68.00" },
    { title: "Bamboo Cutlery Set", sku: "KIT-CUT-BMB", price: "32.00" },
    { title: "Plant-Based Soap Bar", sku: "BTH-SOP-LAV", price: "14.00" },
    { title: "Recycled Glass Vase", sku: "HOM-VAS-CLR", price: "56.00" },
  ];

  return Array.from({ length: end - start + 1 }, (_, i) => {
    const idx = i;
    const num = start + i;
    const customer = customers[idx % customers.length];
    const status = statuses[idx % statuses.length];
    const product = products[idx % products.length];
    const price = Number(product.price) * (1 + (idx % 3));
    const day = 1 + (idx % 28);

    return {
      id: `ord_01HQ00${num.toString().padStart(2, "0")}`,
      storeId,
      shopifyOrderId: `gid://shopify/Order/${5000 + num}`,
      orderNumber: `#${1000 + num}`,
      subtotalPrice: price.toFixed(2),
      totalTax: (price * 0.08).toFixed(2),
      totalShipping: idx % 3 === 0 ? "0.00" : "8.99",
      totalDiscount: idx % 4 === 0 ? (price * 0.1).toFixed(2) : "0.00",
      totalPrice: (price + price * 0.08 + (idx % 3 === 0 ? 0 : 8.99) - (idx % 4 === 0 ? price * 0.1 : 0)).toFixed(2),
      currencyCode: "USD",
      financialStatus: status.fin,
      fulfillmentStatus: status.ful,
      customerEmail: customer.email,
      customerFirstName: customer.first,
      customerLastName: customer.last,
      customerPhone: null,
      shippingAddress: { line1: `${100 + idx} Main St`, line2: null, city: "New York", province: "NY", postalCode: "10001", countryCode: "US", phone: null },
      lineItems: [
        {
          id: `li_gen_${num}`,
          shopifyLineItemId: `gid://shopify/LineItem/${9100 + num}`,
          title: product.title,
          variantTitle: null,
          sku: product.sku,
          quantity: 1 + (idx % 3),
          unitPrice: product.price,
          totalPrice: price.toFixed(2),
          fulfilledQuantity: status.ful === "FULFILLED" ? 1 + (idx % 3) : 0,
        },
      ],
      shipments: status.ful === "FULFILLED"
        ? [{ id: `shp_gen_${num}`, status: "DELIVERED" as const, carrier: "USPS", trackingNumber: `940011189922345678${9000 + num}` }]
        : [],
      createdAt: `2026-03-${day.toString().padStart(2, "0")}T${(8 + (idx % 12)).toString().padStart(2, "0")}:${(idx * 7 % 60).toString().padStart(2, "0")}:00Z`,
      updatedAt: `2026-03-${Math.min(29, day + 2).toString().padStart(2, "0")}T${(10 + (idx % 10)).toString().padStart(2, "0")}:00:00Z`,
    };
  });
}

// ── Shipments ─────────────────────────────────────────────────────────────────

export const mockShipments: Shipment[] = [
  {
    id: "shp_01",
    storeId,
    orderId: "ord_01HQ0001",
    carrier: "USPS",
    service: "Priority Mail",
    trackingNumber: "9400111899223456789012",
    trackingUrl: "https://tools.usps.com/go/TrackConfirmAction?tLabels=9400111899223456789012",
    labelUrl: "https://labels.merchantflow.dev/shp_01.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 850,
    shippedAt: "2026-03-16T10:00:00Z",
    deliveredAt: "2026-03-20T14:30:00Z",
    createdAt: "2026-03-15T14:00:00Z",
    updatedAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "shp_02",
    storeId,
    orderId: "ord_01HQ0002",
    carrier: "UPS",
    service: "Ground",
    trackingNumber: null,
    trackingUrl: null,
    labelUrl: null,
    labelFormat: null,
    status: "PENDING",
    weightGrams: 400,
    shippedAt: null,
    deliveredAt: null,
    createdAt: "2026-03-28T09:00:00Z",
    updatedAt: "2026-03-28T09:00:00Z",
  },
  {
    id: "shp_03",
    storeId,
    orderId: "ord_01HQ0003",
    carrier: "FedEx",
    service: "Home Delivery",
    trackingNumber: "794644790132",
    trackingUrl: "https://www.fedex.com/fedextrack/?trknbr=794644790132",
    labelUrl: "https://labels.merchantflow.dev/shp_03.pdf",
    labelFormat: "PDF",
    status: "SHIPPED",
    weightGrams: 2200,
    shippedAt: "2026-03-25T09:30:00Z",
    deliveredAt: null,
    createdAt: "2026-03-24T16:00:00Z",
    updatedAt: "2026-03-25T09:30:00Z",
  },
  {
    id: "shp_04",
    storeId,
    orderId: "ord_01HQ0005",
    carrier: "USPS",
    service: "Priority Mail Express",
    trackingNumber: "EA123456789US",
    trackingUrl: "https://tools.usps.com/go/TrackConfirmAction?tLabels=EA123456789US",
    labelUrl: "https://labels.merchantflow.dev/shp_04.pdf",
    labelFormat: "PDF",
    status: "IN_TRANSIT",
    weightGrams: 1800,
    shippedAt: "2026-03-26T08:15:00Z",
    deliveredAt: null,
    createdAt: "2026-03-25T15:00:00Z",
    updatedAt: "2026-03-27T12:00:00Z",
  },
  {
    id: "shp_05",
    storeId,
    orderId: "ord_01HQ0005",
    carrier: "UPS",
    service: "2nd Day Air",
    trackingNumber: "1Z999AA10123456784",
    trackingUrl: "https://www.ups.com/track?tracknum=1Z999AA10123456784",
    labelUrl: "https://labels.merchantflow.dev/shp_05.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 1200,
    shippedAt: "2026-03-19T10:00:00Z",
    deliveredAt: "2026-03-21T15:30:00Z",
    createdAt: "2026-03-18T16:00:00Z",
    updatedAt: "2026-03-21T15:30:00Z",
  },
  {
    id: "shp_06",
    storeId,
    orderId: "ord_01HQ0008",
    carrier: "USPS",
    service: "First Class Package",
    trackingNumber: "9400111899223456789099",
    trackingUrl: "https://tools.usps.com/go/TrackConfirmAction?tLabels=9400111899223456789099",
    labelUrl: "https://labels.merchantflow.dev/shp_06.pdf",
    labelFormat: "PDF",
    status: "IN_TRANSIT",
    weightGrams: 600,
    shippedAt: "2026-03-24T14:00:00Z",
    deliveredAt: null,
    createdAt: "2026-03-23T10:00:00Z",
    updatedAt: "2026-03-26T08:00:00Z",
  },
  {
    id: "shp_07",
    storeId,
    orderId: "ord_01HQ0010",
    carrier: "FedEx",
    service: "Ground",
    trackingNumber: "794644790188",
    trackingUrl: "https://www.fedex.com/fedextrack/?trknbr=794644790188",
    labelUrl: "https://labels.merchantflow.dev/shp_07.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 3500,
    shippedAt: "2026-03-14T09:00:00Z",
    deliveredAt: "2026-03-18T16:45:00Z",
    createdAt: "2026-03-13T14:30:00Z",
    updatedAt: "2026-03-18T16:45:00Z",
  },
  {
    id: "shp_08",
    storeId,
    orderId: "ord_01HQ0012",
    carrier: "UPS",
    service: "Ground",
    trackingNumber: "1Z999AA10123456790",
    trackingUrl: "https://www.ups.com/track?tracknum=1Z999AA10123456790",
    labelUrl: "https://labels.merchantflow.dev/shp_08.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 1400,
    shippedAt: "2026-03-15T11:00:00Z",
    deliveredAt: "2026-03-19T10:15:00Z",
    createdAt: "2026-03-14T12:00:00Z",
    updatedAt: "2026-03-19T10:15:00Z",
  },
  {
    id: "shp_09",
    storeId,
    orderId: "ord_01HQ0014",
    carrier: "USPS",
    service: "Priority Mail",
    trackingNumber: "9400111899223456789055",
    trackingUrl: "https://tools.usps.com/go/TrackConfirmAction?tLabels=9400111899223456789055",
    labelUrl: "https://labels.merchantflow.dev/shp_09.pdf",
    labelFormat: "PDF",
    status: "SHIPPED",
    weightGrams: 950,
    shippedAt: "2026-03-23T08:00:00Z",
    deliveredAt: null,
    createdAt: "2026-03-22T16:30:00Z",
    updatedAt: "2026-03-23T08:00:00Z",
  },
  {
    id: "shp_10",
    storeId,
    orderId: "ord_01HQ0007",
    carrier: null,
    service: null,
    trackingNumber: null,
    trackingUrl: null,
    labelUrl: null,
    labelFormat: null,
    status: "LABEL_GENERATING",
    weightGrams: 4200,
    shippedAt: null,
    deliveredAt: null,
    createdAt: "2026-03-29T06:00:00Z",
    updatedAt: "2026-03-29T06:00:00Z",
  },
];

// ── Activity Events ───────────────────────────────────────────────────────────

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: "evt_001",
    type: "order.created",
    title: "New order received",
    description: "Order #1013 placed by Jessica Nguyen for $387.10",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0013",
    timestamp: "2026-03-29T02:10:00Z",
  },
  {
    id: "evt_002",
    type: "webhook.received",
    title: "Webhook received",
    description: "Shopify webhook orders/create processed successfully",
    storeId,
    aggregateType: "webhook",
    aggregateId: "wh_del_001",
    timestamp: "2026-03-29T02:10:01Z",
  },
  {
    id: "evt_003",
    type: "shipment.created",
    title: "Shipment created",
    description: "Shipment shp_10 created for order #1007 — awaiting label generation",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_10",
    timestamp: "2026-03-29T06:00:00Z",
  },
  {
    id: "evt_004",
    type: "order.created",
    title: "New order received",
    description: "Order #1015 placed by Sophia Diaz for $214.79",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0015",
    timestamp: "2026-03-28T22:00:00Z",
  },
  {
    id: "evt_005",
    type: "order.created",
    title: "New order received",
    description: "Order #1011 placed by Rachel Kim for $216.35",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0011",
    timestamp: "2026-03-28T19:30:00Z",
  },
  {
    id: "evt_006",
    type: "order.created",
    title: "New order received",
    description: "Order #1009 placed by Nina Patel for $90.23",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0009",
    timestamp: "2026-03-28T16:55:00Z",
  },
  {
    id: "evt_007",
    type: "sync.completed",
    title: "Store sync completed",
    description: "Synced 12 new orders and 3 product updates from Luminary Goods Co.",
    storeId,
    aggregateType: "store",
    aggregateId: storeId,
    timestamp: "2026-03-28T14:22:00Z",
  },
  {
    id: "evt_008",
    type: "shipment.shipped",
    title: "Shipment shipped",
    description: "Shipment shp_09 for order #1014 marked as shipped via USPS",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_09",
    timestamp: "2026-03-28T08:00:00Z",
  },
  {
    id: "evt_009",
    type: "order.fulfilled",
    title: "Order fulfilled",
    description: "Order #1003 partially fulfilled — 1 of 2 items shipped",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0003",
    timestamp: "2026-03-26T08:15:00Z",
  },
  {
    id: "evt_010",
    type: "shipment.delivered",
    title: "Shipment delivered",
    description: "Shipment shp_06 for order #1008 confirmed delivered via USPS tracking",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_06",
    timestamp: "2026-03-26T08:00:00Z",
  },
  {
    id: "evt_011",
    type: "webhook.delivered",
    title: "Webhook delivered",
    description: "order.fulfilled event delivered to https://hooks.example.com/mf (200 OK)",
    storeId,
    aggregateType: "webhook",
    aggregateId: "wh_del_002",
    timestamp: "2026-03-25T16:00:00Z",
  },
  {
    id: "evt_012",
    type: "shipment.shipped",
    title: "Shipment shipped",
    description: "Shipment shp_03 for order #1003 shipped via FedEx Home Delivery",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_03",
    timestamp: "2026-03-25T09:30:00Z",
  },
  {
    id: "evt_013",
    type: "webhook.failed",
    title: "Webhook delivery failed",
    description: "Failed to deliver order.updated event to https://legacy.example.com/hooks (timeout after 30s)",
    storeId,
    aggregateType: "webhook",
    aggregateId: "wh_del_003",
    timestamp: "2026-03-24T18:00:00Z",
  },
  {
    id: "evt_014",
    type: "product.synced",
    title: "Products synced",
    description: "8 products synced from Luminary Goods Co. — 2 new, 6 updated",
    storeId,
    aggregateType: "store",
    aggregateId: storeId,
    timestamp: "2026-03-24T06:00:00Z",
  },
  {
    id: "evt_015",
    type: "order.updated",
    title: "Order updated",
    description: "Order #1006 refunded — $102.11 returned to customer David Park",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0006",
    timestamp: "2026-03-14T09:00:00Z",
  },
];

// ── Webhook Endpoints ─────────────────────────────────────────────────────────

export const mockWebhookEndpoints: WebhookEndpoint[] = [
  {
    id: "whe_01",
    storeId,
    url: "https://hooks.example.com/merchantflow",
    events: ["order.created", "order.fulfilled", "shipment.shipped", "shipment.delivered"],
    isActive: true,
    failureCount: 0,
    lastSucceededAt: "2026-03-28T14:22:00Z",
    lastFailedAt: null,
    createdAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "whe_02",
    storeId,
    url: "https://legacy.example.com/hooks",
    events: ["order.created", "order.updated"],
    isActive: false,
    failureCount: 5,
    lastSucceededAt: "2026-03-20T08:00:00Z",
    lastFailedAt: "2026-03-24T18:00:00Z",
    createdAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "whe_03",
    storeId,
    url: "https://analytics.example.com/ingest/mf",
    events: ["order.created", "order.updated", "order.fulfilled", "shipment.created", "shipment.shipped", "shipment.delivered"],
    isActive: true,
    failureCount: 1,
    lastSucceededAt: "2026-03-29T02:10:01Z",
    lastFailedAt: "2026-03-22T06:00:00Z",
    createdAt: "2026-02-20T14:00:00Z",
  },
];

// ── Dashboard Stats ───────────────────────────────────────────────────────────

export const mockDashboardStats = {
  totalOrders: 25,
  totalRevenue: 5467.46,
  pendingShipments: 7,
  fulfilledRate: 48,
  revenueChange: 12.5,
  ordersChange: 8.3,
  shipmentsChange: -4.2,
  fulfilledRateChange: 3.1,
};
