import type {
  Store,
  Order,
  Shipment,
  ActivityEvent,
  WebhookEndpoint,
  WebhookDelivery,
} from "@merchantflow/shared-types";

// ── Stores ────────────────────────────────────────────────────────────────────

export const mockStores: Store[] = [
  {
    id: "store_01HQXYZ1A2B3C4D5E6F7G8H9J0",
    name: "Kultura Filipino",
    email: "hello@kulturafilipino.ph",
    shopifyDomain: "kultura-filipino.myshopify.com",
    currency: "PHP",
    timezone: "Asia/Manila",
    status: "ACTIVE",
    createdAt: "2025-11-15T08:30:00Z",
    updatedAt: "2026-03-28T14:22:00Z",
  },
  {
    id: "store_01HQXYZ2B3C4D5E6F7G8H9J0K1",
    name: "Pasalubong Box PH",
    email: "support@pasalubongboxph.com",
    shopifyDomain: "pasalubong-box-ph.myshopify.com",
    currency: "USD",
    timezone: "Asia/Manila",
    status: "ACTIVE",
    createdAt: "2026-01-22T10:15:00Z",
    updatedAt: "2026-03-27T09:45:00Z",
  },
  {
    id: "store_01HQXYZ3C4D5E6F7G8H9J0K1L2",
    name: "Isla Handicrafts",
    email: "hello@islahandicrafts.ph",
    shopifyDomain: "isla-handicrafts.myshopify.com",
    currency: "USD",
    timezone: "Asia/Manila",
    status: "SUSPENDED",
    createdAt: "2026-02-10T06:00:00Z",
    updatedAt: "2026-03-20T12:00:00Z",
  },
];

// ── Orders ────────────────────────────────────────────────────────────────────

const storeId = mockStores[0].id;
const storeId2 = mockStores[1].id;

export const mockOrders: Order[] = [
  // ─── Kultura Filipino orders (PHP, Philippine addresses) ────────────────────
  {
    id: "ord_01HQ0001",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5001",
    orderNumber: "#1001",
    subtotalPrice: "11300.00",
    totalTax: "1356.00",
    totalShipping: "250.00",
    totalDiscount: "0.00",
    totalPrice: "12906.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "maria.santos@example.ph",
    customerFirstName: "Maria",
    customerLastName: "Santos",
    customerPhone: "+639171234567",
    shippingAddress: {
      line1: "Unit 12B, One Salcedo Place",
      line2: "Tordesillas St, Salcedo Village",
      city: "Makati",
      province: "Metro Manila",
      postalCode: "1227",
      countryCode: "PH",
      phone: "+639171234567",
    },
    lineItems: [
      {
        id: "li_001",
        shopifyLineItemId: "gid://shopify/LineItem/9001",
        title: "Barong Tagalog - Jusi Fabric",
        variantTitle: "Large / Ivory",
        sku: "KLT-BRG-JUS-L",
        quantity: 1,
        unitPrice: "4500.00",
        totalPrice: "4500.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_002",
        shopifyLineItemId: "gid://shopify/LineItem/9002",
        title: "Filipiniana Butterfly Sleeve Dress",
        variantTitle: "Medium / Cream",
        sku: "KLT-FLP-BTF-M",
        quantity: 1,
        unitPrice: "6800.00",
        totalPrice: "6800.00",
        fulfilledQuantity: 1,
      },
    ],
    shipments: [
      { id: "shp_01", status: "DELIVERED", carrier: "LBC Express", trackingNumber: "LBC9400111234567890" },
    ],
    createdAt: "2026-03-15T09:12:00Z",
    updatedAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "ord_01HQ0002",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5002",
    orderNumber: "#1002",
    subtotalPrice: "6400.00",
    totalTax: "768.00",
    totalShipping: "200.00",
    totalDiscount: "640.00",
    totalPrice: "6728.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "juan.reyes@example.ph",
    customerFirstName: "Juan",
    customerLastName: "Reyes",
    customerPhone: "+639281234568",
    shippingAddress: {
      line1: "45 A.S. Fortuna St",
      line2: "Banilad",
      city: "Cebu City",
      province: "Cebu",
      postalCode: "6000",
      countryCode: "PH",
      phone: "+639281234568",
    },
    lineItems: [
      {
        id: "li_005",
        shopifyLineItemId: "gid://shopify/LineItem/9005",
        title: "Inabel Woven Blanket - Queen",
        variantTitle: "Earth Tones",
        sku: "KLT-INB-QN-ET",
        quantity: 2,
        unitPrice: "3200.00",
        totalPrice: "6400.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-22T15:45:00Z",
    updatedAt: "2026-03-22T15:45:00Z",
  },
  {
    id: "ord_01HQ0003",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5003",
    orderNumber: "#1003",
    subtotalPrice: "8500.00",
    totalTax: "1020.00",
    totalShipping: "0.00",
    totalDiscount: "850.00",
    totalPrice: "8670.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "PARTIALLY_FULFILLED",
    customerEmail: "ana.cruz@example.ph",
    customerFirstName: "Ana",
    customerLastName: "Cruz",
    customerPhone: null,
    shippingAddress: {
      line1: "88 Katipunan Ave",
      line2: "Loyola Heights",
      city: "Quezon City",
      province: "Metro Manila",
      postalCode: "1108",
      countryCode: "PH",
      phone: null,
    },
    lineItems: [
      {
        id: "li_007",
        shopifyLineItemId: "gid://shopify/LineItem/9007",
        title: "Filipiniana Butterfly Sleeve Dress",
        variantTitle: "Small / Blush Pink",
        sku: "KLT-FLP-BTF-S",
        quantity: 1,
        unitPrice: "6800.00",
        totalPrice: "6800.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_008",
        shopifyLineItemId: "gid://shopify/LineItem/9008",
        title: "Abaca Woven Clutch Bag",
        variantTitle: "Natural",
        sku: "KLT-ABC-CLT-N",
        quantity: 1,
        unitPrice: "1800.00",
        totalPrice: "1800.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [
      { id: "shp_03", status: "SHIPPED", carrier: "J&T Express PH", trackingNumber: "JT2026032500123" },
    ],
    createdAt: "2026-03-24T11:20:00Z",
    updatedAt: "2026-03-26T08:15:00Z",
  },
  {
    id: "ord_01HQ0004",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5004",
    orderNumber: "#1004",
    subtotalPrice: "1500.00",
    totalTax: "180.00",
    totalShipping: "150.00",
    totalDiscount: "0.00",
    totalPrice: "1830.00",
    currencyCode: "PHP",
    financialStatus: "PENDING",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "carlos.garcia@example.ph",
    customerFirstName: "Carlos",
    customerLastName: "Garcia",
    customerPhone: "+639351234570",
    shippingAddress: {
      line1: "Prk. 7, J.P. Laurel Ave",
      line2: "Bajada",
      city: "Davao City",
      province: "Davao del Sur",
      postalCode: "8000",
      countryCode: "PH",
      phone: "+639351234570",
    },
    lineItems: [
      {
        id: "li_009",
        shopifyLineItemId: "gid://shopify/LineItem/9009",
        title: "Piña Cloth Table Runner",
        variantTitle: "6-Seater / Ecru",
        sku: "KLT-PIN-TBR-6",
        quantity: 1,
        unitPrice: "1500.00",
        totalPrice: "1500.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-27T08:30:00Z",
    updatedAt: "2026-03-27T08:30:00Z",
  },
  {
    id: "ord_01HQ0005",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5005",
    orderNumber: "#1005",
    subtotalPrice: "10700.00",
    totalTax: "1284.00",
    totalShipping: "0.00",
    totalDiscount: "1070.00",
    totalPrice: "10914.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "rosa.torres@example.ph",
    customerFirstName: "Rosa",
    customerLastName: "Torres",
    customerPhone: "+639171234571",
    shippingAddress: {
      line1: "5th Ave cor. 26th St",
      line2: "Bonifacio Global City",
      city: "Taguig",
      province: "Metro Manila",
      postalCode: "1634",
      countryCode: "PH",
      phone: "+639171234571",
    },
    lineItems: [
      {
        id: "li_010",
        shopifyLineItemId: "gid://shopify/LineItem/9010",
        title: "Barong Tagalog - Jusi Fabric",
        variantTitle: "XL / Ivory",
        sku: "KLT-BRG-JUS-XL",
        quantity: 1,
        unitPrice: "4500.00",
        totalPrice: "4500.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_011",
        shopifyLineItemId: "gid://shopify/LineItem/9011",
        title: "Terno Blouse - Contemporary",
        variantTitle: "Medium / Dusty Rose",
        sku: "KLT-TRN-CNT-M",
        quantity: 2,
        unitPrice: "2200.00",
        totalPrice: "4400.00",
        fulfilledQuantity: 2,
      },
      {
        id: "li_012",
        shopifyLineItemId: "gid://shopify/LineItem/9012",
        title: "Abaca Woven Clutch Bag",
        variantTitle: "Natural",
        sku: "KLT-ABC-CLT-N",
        quantity: 1,
        unitPrice: "1800.00",
        totalPrice: "1800.00",
        fulfilledQuantity: 1,
      },
    ],
    shipments: [
      { id: "shp_05", status: "DELIVERED", carrier: "LBC Express", trackingNumber: "LBC9400111234567895" },
    ],
    createdAt: "2026-03-18T13:00:00Z",
    updatedAt: "2026-03-23T16:45:00Z",
  },
  {
    id: "ord_01HQ0006",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5006",
    orderNumber: "#1006",
    subtotalPrice: "4500.00",
    totalTax: "540.00",
    totalShipping: "200.00",
    totalDiscount: "0.00",
    totalPrice: "5240.00",
    currencyCode: "PHP",
    financialStatus: "REFUNDED",
    fulfillmentStatus: "RESTOCKED",
    customerEmail: "miguel.ramos@example.ph",
    customerFirstName: "Miguel",
    customerLastName: "Ramos",
    customerPhone: "+639181234572",
    shippingAddress: {
      line1: "24 Pasig Blvd",
      line2: "Brgy. Kapasigan",
      city: "Pasig",
      province: "Metro Manila",
      postalCode: "1600",
      countryCode: "PH",
      phone: "+639181234572",
    },
    lineItems: [
      {
        id: "li_013",
        shopifyLineItemId: "gid://shopify/LineItem/9013",
        title: "Barong Tagalog - Jusi Fabric",
        variantTitle: "Medium / Ivory",
        sku: "KLT-BRG-JUS-M",
        quantity: 1,
        unitPrice: "4500.00",
        totalPrice: "4500.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-10T16:20:00Z",
    updatedAt: "2026-03-14T09:00:00Z",
  },
  {
    id: "ord_01HQ0007",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5007",
    orderNumber: "#1007",
    subtotalPrice: "15800.00",
    totalTax: "1896.00",
    totalShipping: "0.00",
    totalDiscount: "1580.00",
    totalPrice: "16116.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "sofia.delacruz@example.ph",
    customerFirstName: "Sofia",
    customerLastName: "Dela Cruz",
    customerPhone: "+639271234573",
    shippingAddress: {
      line1: "115 L.P. Leviste St",
      line2: "Salcedo Village",
      city: "Makati",
      province: "Metro Manila",
      postalCode: "1227",
      countryCode: "PH",
      phone: "+639271234573",
    },
    lineItems: [
      {
        id: "li_014",
        shopifyLineItemId: "gid://shopify/LineItem/9014",
        title: "Filipiniana Butterfly Sleeve Dress",
        variantTitle: "Large / Ivory",
        sku: "KLT-FLP-BTF-L",
        quantity: 2,
        unitPrice: "6800.00",
        totalPrice: "13600.00",
        fulfilledQuantity: 0,
      },
      {
        id: "li_015",
        shopifyLineItemId: "gid://shopify/LineItem/9015",
        title: "Terno Blouse - Contemporary",
        variantTitle: "Small / Sage Green",
        sku: "KLT-TRN-CNT-S",
        quantity: 1,
        unitPrice: "2200.00",
        totalPrice: "2200.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-28T07:15:00Z",
    updatedAt: "2026-03-28T07:15:00Z",
  },
  {
    id: "ord_01HQ0008",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5008",
    orderNumber: "#1008",
    subtotalPrice: "5000.00",
    totalTax: "600.00",
    totalShipping: "200.00",
    totalDiscount: "0.00",
    totalPrice: "5800.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "jose.villanueva@example.ph",
    customerFirstName: "Jose",
    customerLastName: "Villanueva",
    customerPhone: "+639191234574",
    shippingAddress: {
      line1: "Lot 5, Block 8, Phase 3",
      line2: "Camella Homes, Brgy. Molino",
      city: "Bacoor",
      province: "Cavite",
      postalCode: "4102",
      countryCode: "PH",
      phone: "+639191234574",
    },
    lineItems: [
      {
        id: "li_017",
        shopifyLineItemId: "gid://shopify/LineItem/9017",
        title: "Inabel Woven Blanket - Queen",
        variantTitle: "Indigo Pattern",
        sku: "KLT-INB-QN-IN",
        quantity: 1,
        unitPrice: "3200.00",
        totalPrice: "3200.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_018",
        shopifyLineItemId: "gid://shopify/LineItem/9018",
        title: "Abaca Woven Clutch Bag",
        variantTitle: "Black",
        sku: "KLT-ABC-CLT-B",
        quantity: 1,
        unitPrice: "1800.00",
        totalPrice: "1800.00",
        fulfilledQuantity: 1,
      },
    ],
    shipments: [
      { id: "shp_08", status: "IN_TRANSIT", carrier: "Ninja Van PH", trackingNumber: "NVPH2026032400123" },
    ],
    createdAt: "2026-03-21T10:40:00Z",
    updatedAt: "2026-03-25T11:20:00Z",
  },
  {
    id: "ord_01HQ0009",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5009",
    orderNumber: "#1009",
    subtotalPrice: "2200.00",
    totalTax: "264.00",
    totalShipping: "150.00",
    totalDiscount: "0.00",
    totalPrice: "2614.00",
    currencyCode: "PHP",
    financialStatus: "AUTHORIZED",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "luz.aquino@example.ph",
    customerFirstName: "Luz",
    customerLastName: "Aquino",
    customerPhone: "+639221234575",
    shippingAddress: {
      line1: "34 Gov. M. Cuenco Ave",
      line2: "Banilad",
      city: "Cebu City",
      province: "Cebu",
      postalCode: "6000",
      countryCode: "PH",
      phone: "+639221234575",
    },
    lineItems: [
      {
        id: "li_019",
        shopifyLineItemId: "gid://shopify/LineItem/9019",
        title: "Terno Blouse - Contemporary",
        variantTitle: "Large / Burgundy",
        sku: "KLT-TRN-CNT-L",
        quantity: 1,
        unitPrice: "2200.00",
        totalPrice: "2200.00",
        fulfilledQuantity: 0,
      },
    ],
    shipments: [],
    createdAt: "2026-03-28T16:55:00Z",
    updatedAt: "2026-03-28T16:55:00Z",
  },
  {
    id: "ord_01HQ0010",
    storeId,
    shopifyOrderId: "gid://shopify/Order/5010",
    orderNumber: "#1010",
    subtotalPrice: "18800.00",
    totalTax: "2256.00",
    totalShipping: "0.00",
    totalDiscount: "1880.00",
    totalPrice: "19176.00",
    currencyCode: "PHP",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "pedro.bautista@example.ph",
    customerFirstName: "Pedro",
    customerLastName: "Bautista",
    customerPhone: "+639171234576",
    shippingAddress: {
      line1: "12F Net One Center",
      line2: "26th St cor. 3rd Ave, BGC",
      city: "Taguig",
      province: "Metro Manila",
      postalCode: "1634",
      countryCode: "PH",
      phone: "+639171234576",
    },
    lineItems: [
      {
        id: "li_020",
        shopifyLineItemId: "gid://shopify/LineItem/9020",
        title: "Barong Tagalog - Jusi Fabric",
        variantTitle: "Large / Ivory",
        sku: "KLT-BRG-JUS-L",
        quantity: 2,
        unitPrice: "4500.00",
        totalPrice: "9000.00",
        fulfilledQuantity: 2,
      },
      {
        id: "li_021",
        shopifyLineItemId: "gid://shopify/LineItem/9021",
        title: "Filipiniana Butterfly Sleeve Dress",
        variantTitle: "Medium / Cream",
        sku: "KLT-FLP-BTF-M",
        quantity: 1,
        unitPrice: "6800.00",
        totalPrice: "6800.00",
        fulfilledQuantity: 1,
      },
      {
        id: "li_022",
        shopifyLineItemId: "gid://shopify/LineItem/9022",
        title: "Piña Cloth Table Runner",
        variantTitle: "8-Seater / Ecru",
        sku: "KLT-PIN-TBR-8",
        quantity: 2,
        unitPrice: "1500.00",
        totalPrice: "3000.00",
        fulfilledQuantity: 2,
      },
    ],
    shipments: [
      { id: "shp_10", status: "DELIVERED", carrier: "J&T Express PH", trackingNumber: "JT2026031400188" },
    ],
    createdAt: "2026-03-12T14:10:00Z",
    updatedAt: "2026-03-19T09:30:00Z",
  },
  // ─── Pasalubong Box PH orders (USD, international addresses) ────────────────
  {
    id: "ord_01HQ0011",
    storeId: storeId2,
    shopifyOrderId: "gid://shopify/Order/5011",
    orderNumber: "#1011",
    subtotalPrice: "50.97",
    totalTax: "4.08",
    totalShipping: "12.99",
    totalDiscount: "0.00",
    totalPrice: "68.04",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "elena.gonzales@example.com",
    customerFirstName: "Elena",
    customerLastName: "Gonzales",
    customerPhone: "+1-213-555-0188",
    shippingAddress: { line1: "4521 Wilshire Blvd", line2: "Apt 8C", city: "Los Angeles", province: "CA", postalCode: "90010", countryCode: "US", phone: "+1-213-555-0188" },
    lineItems: [
      { id: "li_024", shopifyLineItemId: "gid://shopify/LineItem/9024", title: "Dried Philippine Mango - 500g", variantTitle: null, sku: "PSB-DPM-500", quantity: 2, unitPrice: "12.99", totalPrice: "25.98", fulfilledQuantity: 0 },
      { id: "li_025", shopifyLineItemId: "gid://shopify/LineItem/9025", title: "Polvoron Assorted Box (24pc)", variantTitle: null, sku: "PSB-POL-24", quantity: 1, unitPrice: "18.99", totalPrice: "18.99", fulfilledQuantity: 0 },
      { id: "li_026", shopifyLineItemId: "gid://shopify/LineItem/9026", title: "Banana Chips - Sea Salt (300g)", variantTitle: null, sku: "PSB-BCS-300", quantity: 1, unitPrice: "7.99", totalPrice: "7.99", fulfilledQuantity: 0 },
    ],
    shipments: [],
    createdAt: "2026-03-28T19:30:00Z",
    updatedAt: "2026-03-28T19:30:00Z",
  },
  {
    id: "ord_01HQ0012",
    storeId: storeId2,
    shopifyOrderId: "gid://shopify/Order/5012",
    orderNumber: "#1012",
    subtotalPrice: "40.97",
    totalTax: "3.28",
    totalShipping: "14.99",
    totalDiscount: "0.00",
    totalPrice: "59.24",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "ramon.rivera@example.com",
    customerFirstName: "Ramon",
    customerLastName: "Rivera",
    customerPhone: "+1-212-555-0199",
    shippingAddress: { line1: "350 5th Avenue", line2: "Suite 4400", city: "New York", province: "NY", postalCode: "10118", countryCode: "US", phone: "+1-212-555-0199" },
    lineItems: [
      { id: "li_028", shopifyLineItemId: "gid://shopify/LineItem/9028", title: "Ube Halaya Spread - 340g", variantTitle: null, sku: "PSB-UBE-340", quantity: 2, unitPrice: "9.99", totalPrice: "19.98", fulfilledQuantity: 2 },
      { id: "li_029", shopifyLineItemId: "gid://shopify/LineItem/9029", title: "Dried Philippine Mango - 500g", variantTitle: null, sku: "PSB-DPM-500", quantity: 1, unitPrice: "12.99", totalPrice: "12.99", fulfilledQuantity: 1 },
      { id: "li_030", shopifyLineItemId: "gid://shopify/LineItem/9030", title: "Chicharon Bulacan - Original (250g)", variantTitle: null, sku: "PSB-CCB-250", quantity: 1, unitPrice: "8.99", totalPrice: "8.99", fulfilledQuantity: 1 },
    ],
    shipments: [
      { id: "shp_12", status: "DELIVERED", carrier: "DHL Express", trackingNumber: "DHL1234567890" },
    ],
    createdAt: "2026-03-14T08:00:00Z",
    updatedAt: "2026-03-20T10:15:00Z",
  },
  {
    id: "ord_01HQ0013",
    storeId: storeId2,
    shopifyOrderId: "gid://shopify/Order/5013",
    orderNumber: "#1013",
    subtotalPrice: "68.95",
    totalTax: "5.52",
    totalShipping: "0.00",
    totalDiscount: "6.90",
    totalPrice: "67.57",
    currencyCode: "USD",
    financialStatus: "PARTIALLY_PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "isabella.martinez@example.com",
    customerFirstName: "Isabella",
    customerLastName: "Martinez",
    customerPhone: "+1-415-555-0145",
    shippingAddress: { line1: "1200 Market St", line2: "Unit 12A", city: "San Francisco", province: "CA", postalCode: "94103", countryCode: "US", phone: "+1-415-555-0145" },
    lineItems: [
      { id: "li_031", shopifyLineItemId: "gid://shopify/LineItem/9031", title: "Polvoron Assorted Box (24pc)", variantTitle: null, sku: "PSB-POL-24", quantity: 2, unitPrice: "18.99", totalPrice: "37.98", fulfilledQuantity: 0 },
      { id: "li_032", shopifyLineItemId: "gid://shopify/LineItem/9032", title: "Dried Philippine Mango - 500g", variantTitle: null, sku: "PSB-DPM-500", quantity: 1, unitPrice: "12.99", totalPrice: "12.99", fulfilledQuantity: 0 },
      { id: "li_033", shopifyLineItemId: "gid://shopify/LineItem/9033", title: "Polvoron Assorted Box (24pc)", variantTitle: null, sku: "PSB-POL-24", quantity: 1, unitPrice: "18.99", totalPrice: "18.99", fulfilledQuantity: 0 },
    ],
    shipments: [],
    createdAt: "2026-03-29T02:10:00Z",
    updatedAt: "2026-03-29T02:10:00Z",
  },
  {
    id: "ord_01HQ0014",
    storeId: storeId2,
    shopifyOrderId: "gid://shopify/Order/5014",
    orderNumber: "#1014",
    subtotalPrice: "26.97",
    totalTax: "2.16",
    totalShipping: "9.99",
    totalDiscount: "0.00",
    totalPrice: "39.12",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "FULFILLED",
    customerEmail: "david.lopez@example.com",
    customerFirstName: "David",
    customerLastName: "Lopez",
    customerPhone: "+1-416-555-0132",
    shippingAddress: { line1: "220 Yonge St", line2: "Suite 300", city: "Toronto", province: "ON", postalCode: "M5B 2H1", countryCode: "CA", phone: "+1-416-555-0132" },
    lineItems: [
      { id: "li_034", shopifyLineItemId: "gid://shopify/LineItem/9034", title: "Chicharon Bulacan - Original (250g)", variantTitle: null, sku: "PSB-CCB-250", quantity: 3, unitPrice: "8.99", totalPrice: "26.97", fulfilledQuantity: 3 },
    ],
    shipments: [
      { id: "shp_14", status: "SHIPPED", carrier: "FedEx", trackingNumber: "FEDEX794644790055" },
    ],
    createdAt: "2026-03-19T12:35:00Z",
    updatedAt: "2026-03-24T08:00:00Z",
  },
  {
    id: "ord_01HQ0015",
    storeId: storeId2,
    shopifyOrderId: "gid://shopify/Order/5015",
    orderNumber: "#1015",
    subtotalPrice: "58.96",
    totalTax: "4.72",
    totalShipping: "14.99",
    totalDiscount: "5.90",
    totalPrice: "72.77",
    currencyCode: "USD",
    financialStatus: "PAID",
    fulfillmentStatus: "UNFULFILLED",
    customerEmail: "carmen.fernandez@example.com",
    customerFirstName: "Carmen",
    customerLastName: "Fernandez",
    customerPhone: "+971-55-555-0178",
    shippingAddress: { line1: "Al Barsha Heights", line2: "Tower B, Apt 2103", city: "Dubai", province: "Dubai", postalCode: "00000", countryCode: "AE", phone: "+971-55-555-0178" },
    lineItems: [
      { id: "li_035", shopifyLineItemId: "gid://shopify/LineItem/9035", title: "Dried Philippine Mango - 500g", variantTitle: null, sku: "PSB-DPM-500", quantity: 1, unitPrice: "12.99", totalPrice: "12.99", fulfilledQuantity: 0 },
      { id: "li_036", shopifyLineItemId: "gid://shopify/LineItem/9036", title: "Ube Halaya Spread - 340g", variantTitle: null, sku: "PSB-UBE-340", quantity: 2, unitPrice: "9.99", totalPrice: "19.98", fulfilledQuantity: 0 },
      { id: "li_037", shopifyLineItemId: "gid://shopify/LineItem/9037", title: "Polvoron Assorted Box (24pc)", variantTitle: null, sku: "PSB-POL-24", quantity: 1, unitPrice: "18.99", totalPrice: "18.99", fulfilledQuantity: 0 },
      { id: "li_038", shopifyLineItemId: "gid://shopify/LineItem/9038", title: "Banana Chips - Sea Salt (300g)", variantTitle: null, sku: "PSB-BCS-300", quantity: 1, unitPrice: "7.99", totalPrice: "7.99", fulfilledQuantity: 0 },
    ],
    shipments: [],
    createdAt: "2026-03-28T22:00:00Z",
    updatedAt: "2026-03-28T22:00:00Z",
  },
  // Additional orders for pagination
  ...generateBulkOrders(16, 25),
];

function generateBulkOrders(start: number, end: number): Order[] {
  const kulturaCustomers = [
    { first: "Patricia", last: "Santos", email: "patricia.santos@example.ph" },
    { first: "Angelo", last: "Reyes", email: "angelo.reyes@example.ph" },
    { first: "Katrina", last: "Dela Cruz", email: "katrina.delacruz@example.ph" },
    { first: "Rafael", last: "Gonzales", email: "rafael.gonzales@example.ph" },
    { first: "Jasmine", last: "Villanueva", email: "jasmine.villanueva@example.ph" },
  ];

  const pasalubongCustomers = [
    { first: "Paolo", last: "Garcia", email: "paolo.garcia@example.com" },
    { first: "Bianca", last: "Cruz", email: "bianca.cruz@example.com" },
    { first: "Marco", last: "Fernandez", email: "marco.fernandez@example.com" },
    { first: "Gabriella", last: "Aquino", email: "gabriella.aquino@example.com" },
    { first: "Kevin", last: "Ramos", email: "kevin.ramos@example.com" },
  ];

  const statuses: Array<{ fin: Order["financialStatus"]; ful: Order["fulfillmentStatus"] }> = [
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "PAID", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "PARTIALLY_FULFILLED" },
    { fin: "PENDING", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "AUTHORIZED", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "PAID", ful: "UNFULFILLED" },
    { fin: "PAID", ful: "FULFILLED" },
    { fin: "PARTIALLY_REFUNDED", ful: "FULFILLED" },
  ];

  const kulturaProducts = [
    { title: "Barong Tagalog - Jusi Fabric", sku: "KLT-BRG-JUS-M", price: "4500.00" },
    { title: "Inabel Woven Blanket - Queen", sku: "KLT-INB-QN-ET", price: "3200.00" },
    { title: "Terno Blouse - Contemporary", sku: "KLT-TRN-CNT-M", price: "2200.00" },
    { title: "Piña Cloth Table Runner", sku: "KLT-PIN-TBR-6", price: "1500.00" },
    { title: "Abaca Woven Clutch Bag", sku: "KLT-ABC-CLT-N", price: "1800.00" },
  ];

  const pasalubongProducts = [
    { title: "Dried Philippine Mango - 500g", sku: "PSB-DPM-500", price: "12.99" },
    { title: "Polvoron Assorted Box (24pc)", sku: "PSB-POL-24", price: "18.99" },
    { title: "Chicharon Bulacan - Original (250g)", sku: "PSB-CCB-250", price: "8.99" },
    { title: "Ube Halaya Spread - 340g", sku: "PSB-UBE-340", price: "9.99" },
    { title: "Banana Chips - Sea Salt (300g)", sku: "PSB-BCS-300", price: "7.99" },
  ];

  const phAddresses = [
    { line1: "21 Jupiter St, Bel-Air", city: "Makati", province: "Metro Manila", postalCode: "1209" },
    { line1: "56 Osmeña Blvd", city: "Cebu City", province: "Cebu", postalCode: "6000" },
    { line1: "Block 7, Lot 3, BF Homes", city: "Parañaque", province: "Metro Manila", postalCode: "1720" },
    { line1: "Prk. Narra, Ma-a Road", city: "Davao City", province: "Davao del Sur", postalCode: "8000" },
    { line1: "78 Scout Borromeo St", city: "Quezon City", province: "Metro Manila", postalCode: "1103" },
  ];

  const intlAddresses = [
    { line1: "88 Colin P Kelly Jr St", city: "San Francisco", province: "CA", postalCode: "94107", countryCode: "US" },
    { line1: "100 King St W", city: "Toronto", province: "ON", postalCode: "M5X 1A9", countryCode: "CA" },
    { line1: "1 Raffles Place", city: "Singapore", province: "Singapore", postalCode: "048616", countryCode: "SG" },
    { line1: "200 George St", city: "Sydney", province: "NSW", postalCode: "2000", countryCode: "AU" },
    { line1: "520 Madison Ave", city: "New York", province: "NY", postalCode: "10022", countryCode: "US" },
  ];

  const phCarriers = ["LBC Express", "J&T Express PH", "JRS Express", "Ninja Van PH"];
  const intlCarriers = ["DHL Express", "FedEx"];

  return Array.from({ length: end - start + 1 }, (_, i) => {
    const idx = i;
    const num = start + i;
    const isKultura = idx % 2 === 0;
    const customer = isKultura
      ? kulturaCustomers[idx % kulturaCustomers.length]
      : pasalubongCustomers[idx % pasalubongCustomers.length];
    const status = statuses[idx % statuses.length];
    const product = isKultura
      ? kulturaProducts[idx % kulturaProducts.length]
      : pasalubongProducts[idx % pasalubongProducts.length];
    const price = Number(product.price) * (1 + (idx % 3));
    const currency = isKultura ? "PHP" : "USD";
    const day = 1 + (idx % 28);
    const addr = isKultura
      ? phAddresses[idx % phAddresses.length]
      : intlAddresses[idx % intlAddresses.length];
    const carrier = isKultura
      ? phCarriers[idx % phCarriers.length]
      : intlCarriers[idx % intlCarriers.length];

    return {
      id: `ord_01HQ00${num.toString().padStart(2, "0")}`,
      storeId: isKultura ? storeId : storeId2,
      shopifyOrderId: `gid://shopify/Order/${5000 + num}`,
      orderNumber: `#${1000 + num}`,
      subtotalPrice: price.toFixed(2),
      totalTax: (price * 0.12).toFixed(2),
      totalShipping: idx % 3 === 0 ? "0.00" : isKultura ? "250.00" : "14.99",
      totalDiscount: idx % 4 === 0 ? (price * 0.1).toFixed(2) : "0.00",
      totalPrice: (price + price * 0.12 + (idx % 3 === 0 ? 0 : isKultura ? 250 : 14.99) - (idx % 4 === 0 ? price * 0.1 : 0)).toFixed(2),
      currencyCode: currency,
      financialStatus: status.fin,
      fulfillmentStatus: status.ful,
      customerEmail: customer.email,
      customerFirstName: customer.first,
      customerLastName: customer.last,
      customerPhone: null,
      shippingAddress: {
        line1: addr.line1,
        line2: null,
        city: addr.city,
        province: addr.province,
        postalCode: addr.postalCode,
        countryCode: isKultura ? "PH" : (addr as { countryCode?: string }).countryCode ?? "US",
        phone: null,
      },
      lineItems: [
        {
          id: `li_gen_${num}`,
          shopifyLineItemId: `gid://shopify/LineItem/${9100 + num}`,
          title: product.title,
          variantTitle: null,
          sku: product.sku,
          quantity: 1 + (idx % 3),
          unitPrice: product.price,
          totalPrice: price.toFixed(2),
          fulfilledQuantity: status.ful === "FULFILLED" ? 1 + (idx % 3) : 0,
        },
      ],
      shipments: status.ful === "FULFILLED"
        ? [{ id: `shp_gen_${num}`, status: "DELIVERED" as const, carrier, trackingNumber: `TRK${carrier.replace(/\s/g, "").toUpperCase()}${9000 + num}` }]
        : [],
      createdAt: `2026-03-${day.toString().padStart(2, "0")}T${(8 + (idx % 12)).toString().padStart(2, "0")}:${(idx * 7 % 60).toString().padStart(2, "0")}:00Z`,
      updatedAt: `2026-03-${Math.min(29, day + 2).toString().padStart(2, "0")}T${(10 + (idx % 10)).toString().padStart(2, "0")}:00:00Z`,
    };
  });
}

// ── Shipments ─────────────────────────────────────────────────────────────────

export const mockShipments: Shipment[] = [
  {
    id: "shp_01",
    storeId,
    orderId: "ord_01HQ0001",
    carrier: "LBC Express",
    service: "Metro Manila Same-Day",
    trackingNumber: "LBC9400111234567890",
    trackingUrl: "https://www.lbcexpress.com/track/?tracking_no=LBC9400111234567890",
    labelUrl: "https://labels.merchantflow.dev/shp_01.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 850,
    shippedAt: "2026-03-16T10:00:00Z",
    deliveredAt: "2026-03-20T14:30:00Z",
    createdAt: "2026-03-15T14:00:00Z",
    updatedAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "shp_02",
    storeId,
    orderId: "ord_01HQ0002",
    carrier: "JRS Express",
    service: "VisMin Delivery",
    trackingNumber: null,
    trackingUrl: null,
    labelUrl: null,
    labelFormat: null,
    status: "PENDING",
    weightGrams: 1200,
    shippedAt: null,
    deliveredAt: null,
    createdAt: "2026-03-28T09:00:00Z",
    updatedAt: "2026-03-28T09:00:00Z",
  },
  {
    id: "shp_03",
    storeId,
    orderId: "ord_01HQ0003",
    carrier: "J&T Express PH",
    service: "Standard Delivery",
    trackingNumber: "JT2026032500123",
    trackingUrl: "https://www.jtexpress.ph/trajectoryQuery?billcode=JT2026032500123",
    labelUrl: "https://labels.merchantflow.dev/shp_03.pdf",
    labelFormat: "PDF",
    status: "SHIPPED",
    weightGrams: 600,
    shippedAt: "2026-03-25T09:30:00Z",
    deliveredAt: null,
    createdAt: "2026-03-24T16:00:00Z",
    updatedAt: "2026-03-25T09:30:00Z",
  },
  {
    id: "shp_04",
    storeId,
    orderId: "ord_01HQ0005",
    carrier: "Ninja Van PH",
    service: "Next-Day Delivery",
    trackingNumber: "NVPH2026032600001",
    trackingUrl: "https://www.ninjavan.co/ph-en/tracking?id=NVPH2026032600001",
    labelUrl: "https://labels.merchantflow.dev/shp_04.pdf",
    labelFormat: "PDF",
    status: "IN_TRANSIT",
    weightGrams: 1800,
    shippedAt: "2026-03-26T08:15:00Z",
    deliveredAt: null,
    createdAt: "2026-03-25T15:00:00Z",
    updatedAt: "2026-03-27T12:00:00Z",
  },
  {
    id: "shp_05",
    storeId,
    orderId: "ord_01HQ0005",
    carrier: "LBC Express",
    service: "Metro Manila Express",
    trackingNumber: "LBC9400111234567895",
    trackingUrl: "https://www.lbcexpress.com/track/?tracking_no=LBC9400111234567895",
    labelUrl: "https://labels.merchantflow.dev/shp_05.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 1200,
    shippedAt: "2026-03-19T10:00:00Z",
    deliveredAt: "2026-03-21T15:30:00Z",
    createdAt: "2026-03-18T16:00:00Z",
    updatedAt: "2026-03-21T15:30:00Z",
  },
  {
    id: "shp_06",
    storeId,
    orderId: "ord_01HQ0008",
    carrier: "Ninja Van PH",
    service: "Standard Delivery",
    trackingNumber: "NVPH2026032400123",
    trackingUrl: "https://www.ninjavan.co/ph-en/tracking?id=NVPH2026032400123",
    labelUrl: "https://labels.merchantflow.dev/shp_06.pdf",
    labelFormat: "PDF",
    status: "IN_TRANSIT",
    weightGrams: 1400,
    shippedAt: "2026-03-24T14:00:00Z",
    deliveredAt: null,
    createdAt: "2026-03-23T10:00:00Z",
    updatedAt: "2026-03-26T08:00:00Z",
  },
  {
    id: "shp_07",
    storeId,
    orderId: "ord_01HQ0010",
    carrier: "J&T Express PH",
    service: "Standard Delivery",
    trackingNumber: "JT2026031400188",
    trackingUrl: "https://www.jtexpress.ph/trajectoryQuery?billcode=JT2026031400188",
    labelUrl: "https://labels.merchantflow.dev/shp_07.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 3500,
    shippedAt: "2026-03-14T09:00:00Z",
    deliveredAt: "2026-03-18T16:45:00Z",
    createdAt: "2026-03-13T14:30:00Z",
    updatedAt: "2026-03-18T16:45:00Z",
  },
  {
    id: "shp_08",
    storeId: storeId2,
    orderId: "ord_01HQ0012",
    carrier: "DHL Express",
    service: "Express Worldwide",
    trackingNumber: "DHL1234567890",
    trackingUrl: "https://www.dhl.com/en/express/tracking.html?AWB=DHL1234567890",
    labelUrl: "https://labels.merchantflow.dev/shp_08.pdf",
    labelFormat: "PDF",
    status: "DELIVERED",
    weightGrams: 2800,
    shippedAt: "2026-03-15T11:00:00Z",
    deliveredAt: "2026-03-19T10:15:00Z",
    createdAt: "2026-03-14T12:00:00Z",
    updatedAt: "2026-03-19T10:15:00Z",
  },
  {
    id: "shp_09",
    storeId: storeId2,
    orderId: "ord_01HQ0014",
    carrier: "FedEx",
    service: "International Priority",
    trackingNumber: "FEDEX794644790055",
    trackingUrl: "https://www.fedex.com/fedextrack/?trknbr=FEDEX794644790055",
    labelUrl: "https://labels.merchantflow.dev/shp_09.pdf",
    labelFormat: "PDF",
    status: "SHIPPED",
    weightGrams: 950,
    shippedAt: "2026-03-23T08:00:00Z",
    deliveredAt: null,
    createdAt: "2026-03-22T16:30:00Z",
    updatedAt: "2026-03-23T08:00:00Z",
  },
  {
    id: "shp_10",
    storeId,
    orderId: "ord_01HQ0007",
    carrier: null,
    service: null,
    trackingNumber: null,
    trackingUrl: null,
    labelUrl: null,
    labelFormat: null,
    status: "LABEL_GENERATING",
    weightGrams: 2200,
    shippedAt: null,
    deliveredAt: null,
    createdAt: "2026-03-29T06:00:00Z",
    updatedAt: "2026-03-29T06:00:00Z",
  },
];

// ── Activity Events ───────────────────────────────────────────────────────────

export const mockActivityEvents: ActivityEvent[] = [
  {
    id: "evt_001",
    type: "order.created",
    title: "New order received",
    description: "Order #1013 placed by Isabella Martinez — Polvoron Assorted Box + Dried Mango — $67.57",
    storeId: storeId2,
    aggregateType: "order",
    aggregateId: "ord_01HQ0013",
    timestamp: "2026-03-29T02:10:00Z",
  },
  {
    id: "evt_002",
    type: "webhook.received",
    title: "Webhook received",
    description: "Shopify webhook orders/create from Pasalubong Box PH processed successfully",
    storeId: storeId2,
    aggregateType: "webhook",
    aggregateId: "wh_del_001",
    timestamp: "2026-03-29T02:10:01Z",
  },
  {
    id: "evt_003",
    type: "shipment.created",
    title: "Shipment created",
    description: "Shipment shp_10 created for order #1007 (Filipiniana Butterfly Sleeve Dress x2) — awaiting label generation",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_10",
    timestamp: "2026-03-29T06:00:00Z",
  },
  {
    id: "evt_004",
    type: "order.created",
    title: "New order received",
    description: "Order #1015 placed by Carmen Fernandez — Dried Mango, Ube Halaya, Polvoron, Banana Chips — $72.77",
    storeId: storeId2,
    aggregateType: "order",
    aggregateId: "ord_01HQ0015",
    timestamp: "2026-03-28T22:00:00Z",
  },
  {
    id: "evt_005",
    type: "order.created",
    title: "New order received",
    description: "Order #1011 placed by Elena Gonzales — Dried Mango + Polvoron + Banana Chips — $68.04",
    storeId: storeId2,
    aggregateType: "order",
    aggregateId: "ord_01HQ0011",
    timestamp: "2026-03-28T19:30:00Z",
  },
  {
    id: "evt_006",
    type: "order.created",
    title: "New order received",
    description: "Order #1009 placed by Luz Aquino — Terno Blouse Contemporary — ₱2,614.00",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0009",
    timestamp: "2026-03-28T16:55:00Z",
  },
  {
    id: "evt_007",
    type: "sync.completed",
    title: "Store sync completed",
    description: "Synced 12 new orders and 3 product updates from Kultura Filipino",
    storeId,
    aggregateType: "store",
    aggregateId: storeId,
    timestamp: "2026-03-28T14:22:00Z",
  },
  {
    id: "evt_008",
    type: "shipment.shipped",
    title: "Shipment shipped",
    description: "Shipment shp_09 for order #1014 (Chicharon Bulacan x3) shipped via FedEx to Toronto",
    storeId: storeId2,
    aggregateType: "shipment",
    aggregateId: "shp_09",
    timestamp: "2026-03-28T08:00:00Z",
  },
  {
    id: "evt_009",
    type: "order.fulfilled",
    title: "Order fulfilled",
    description: "Order #1003 partially fulfilled — Filipiniana Dress shipped, Abaca Clutch Bag pending",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0003",
    timestamp: "2026-03-26T08:15:00Z",
  },
  {
    id: "evt_010",
    type: "shipment.delivered",
    title: "Shipment delivered",
    description: "Shipment shp_06 for order #1008 (Inabel Blanket + Abaca Clutch) confirmed delivered via Ninja Van PH",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_06",
    timestamp: "2026-03-26T08:00:00Z",
  },
  {
    id: "evt_011",
    type: "webhook.delivered",
    title: "Webhook delivered",
    description: "order.fulfilled event delivered to https://hooks.example.com/mf (200 OK)",
    storeId,
    aggregateType: "webhook",
    aggregateId: "wh_del_002",
    timestamp: "2026-03-25T16:00:00Z",
  },
  {
    id: "evt_012",
    type: "shipment.shipped",
    title: "Shipment shipped",
    description: "Shipment shp_03 for order #1003 shipped via J&T Express PH — Filipiniana Butterfly Sleeve Dress",
    storeId,
    aggregateType: "shipment",
    aggregateId: "shp_03",
    timestamp: "2026-03-25T09:30:00Z",
  },
  {
    id: "evt_013",
    type: "webhook.failed",
    title: "Webhook delivery failed",
    description: "Failed to deliver order.updated event to https://legacy.example.com/hooks (timeout after 30s)",
    storeId,
    aggregateType: "webhook",
    aggregateId: "wh_del_003",
    timestamp: "2026-03-24T18:00:00Z",
  },
  {
    id: "evt_014",
    type: "product.synced",
    title: "Products synced",
    description: "6 products synced from Kultura Filipino — Barong, Filipiniana, Inabel, Abaca Clutch, Terno, Piña Runner",
    storeId,
    aggregateType: "store",
    aggregateId: storeId,
    timestamp: "2026-03-24T06:00:00Z",
  },
  {
    id: "evt_015",
    type: "order.updated",
    title: "Order updated",
    description: "Order #1006 refunded — ₱5,240.00 returned to customer Miguel Ramos (Barong Tagalog)",
    storeId,
    aggregateType: "order",
    aggregateId: "ord_01HQ0006",
    timestamp: "2026-03-14T09:00:00Z",
  },
];

// ── Webhook Endpoints ─────────────────────────────────────────────────────────

export const mockWebhookEndpoints: WebhookEndpoint[] = [
  {
    id: "whe_01",
    storeId,
    url: "https://hooks.example.com/merchantflow",
    events: ["order.created", "order.fulfilled", "shipment.shipped", "shipment.delivered"],
    isActive: true,
    failureCount: 0,
    lastSucceededAt: "2026-03-28T14:22:00Z",
    lastFailedAt: null,
    createdAt: "2025-12-01T10:00:00Z",
  },
  {
    id: "whe_02",
    storeId,
    url: "https://legacy.example.com/hooks",
    events: ["order.created", "order.updated"],
    isActive: false,
    failureCount: 5,
    lastSucceededAt: "2026-03-20T08:00:00Z",
    lastFailedAt: "2026-03-24T18:00:00Z",
    createdAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "whe_03",
    storeId,
    url: "https://analytics.example.com/ingest/mf",
    events: ["order.created", "order.updated", "order.fulfilled", "shipment.created", "shipment.shipped", "shipment.delivered"],
    isActive: true,
    failureCount: 1,
    lastSucceededAt: "2026-03-29T02:10:01Z",
    lastFailedAt: "2026-03-22T06:00:00Z",
    createdAt: "2026-02-20T14:00:00Z",
  },
];

// ── Dashboard Stats ───────────────────────────────────────────────────────────

export const mockDashboardStats = {
  totalOrders: 25,
  totalRevenue: 2847500,
  pendingShipments: 7,
  fulfilledRate: 48,
  revenueChange: 12.5,
  ordersChange: 8.3,
  shipmentsChange: -4.2,
  fulfilledRateChange: 3.1,
};
